print("Welcome to Band Name Generator.")
a = input("What's the name of city you grew up in?\n")
print(a)
b = input("What's your pet's name?\n")
print(b)
print("Your Band Name could be " +a+" " + b + " .")
